2023-09-23 12:29:05,766 ERROR Internal Server Error: /news/ C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x000001CB189E0880>)
Traceback (most recent call last):
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\NewsPortal_django\newsportalapp\views.py", line 189, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
2023-09-23 12:29:05,769 ERROR "GET /news/ HTTP/1.1" 500 137485 C:\Users\οκ\PycharmProjects\NewsPortal\newsportal\lib\site-packages\django\core\servers\basehttp.py None
